apiVersion: v1
kind: Secret
metadata:
  name: djangoapp-secrets
  labels:
    {{- include "base_labels" . | indent 4 }}
    {{ .Values.appIdentifier }}: {{ .Values.django.app }}
type: Opaque
data:
  {{- range $key,$value :=  .Values.env.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}