apiVersion: apps/v1
kind: Deployment
{{- include "django_metadata" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    {{- include "django_metadata" . | indent 4 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/djangoapp-configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/djangoapp-secrets.yaml") . | sha256sum }}
    spec:
      containers:
        envFrom:
        - configMapRef:
            name: djangoapp-configmap
        - secretRef:
            name: djangoapp-secrets
        name: djangoapp-django
        image: {{  .Values.django.djangoappImage }}:{{ required "Missing .Chart.appVersion" .Chart.AppVersion }}
        resources:
          limits:
            cpu: {{ .Values.django.cpuLimit | quote }}
            memory: {{ .Values.django.memoryLimit | quote }}
          requests:
            cpu: {{ .Values.django.cpuRequest | quote }}
            memory: {{ .Values.django.memoryRequest | quote}}
