apiVersion: v1
kind: Secret
metadata:
  name: djangoapp-secrets
  labels:
    {{- include "base_labels" . | indent 4 }}
    {{ .Values.appIdentifier }}: {{ .Values.django.app }}
type: Opaque
data:
  # these are stored in a decrypted yaml file under `env.secrets`
  # under keys corresponding to the env name, most notably
  # DJANGO_APP_DB_USER, DJANGO_APP_DB_PASSWORD
  {{- range $key,$value :=  .Values.env.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
