apiVersion: v1
kind: Service
metadata:
{{- include "django_metadata" . }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.env.loadbalancerIP }}
  ports:
  - port: {{ .Values.django.externalPort }}
    targetPort: {{ .Values.django.workersPort }}
  selector:
    {{- include "django_labels" . | indent 4 }}
