apiVersion: apps/v1
kind: Deployment
{{- include "redis_slave_metadata" . }}
spec:
  replicas: 1
  template:
    {{- include "redis_slave_metadata" . | indent 4 }}
    spec:
      containers:
      - name: slave
        image: {{ .Values.redis.image }}
        command: ["redis-server",  "--slaveof",  "djangoapp-redis-master",  "6379"]
        ports:
        - containerPort: {{ .Values.redis.port }}
        resources:
          limits:
            cpu: {{ .Values.redis.cpuLimit | quote }}
            memory: {{ .Values.redis.memoryLimit | quote }}
          requests:
            cpu: {{ .Values.redis.cpuRequest | quote }}
            memory: {{ .Values.redis.memoryRequest | quote}}
