env:
  dbIpAddress: <DB_IP_ADDRESS>
  dbName: <DB_NAME>
  staticFiles: "https://storage.googleapis.com/<MY_BUCKET>/static/"
  djangoappLogLevel: "DEBUG"

  # external static IP of the main loadbalancer
  loadbalancerIP: <RESERVED_IP>

  # this is consumed by djangoapp worker, but is a secret
  # should be ideally in a separated encrypted file so 
  # you can version it but it's encrypted
  secrets:
    SECRET_KEY: "xxx"
    DJANGO_APP_DB_USER: "###"
    DJANGO_APP_DB_PASSWORD: "###"
